### ISSUE TITLE
I can not use it

### ISSUE THREAD

**Issue by tyl569** [eleventigers/mitsuku-api#3]
你好，我现在不能使用这个项目，运行的时候，提示"Unhandled rejection Error: getaddrinfo ENOTFOUND fiddle.pandorabots.com fiddle.pandorabots.com:80"，这个项目是被关闭了吗？

**Comment by eleventigers** [comment]
Fixed in: https://github.com/eleventigers/mitsuku-api/commit/07f70565e606e757d6a306685a5b0f4b7c395285

**Comment by tyl569** [comment]
oh, Thank u very much
