### ISSUE TITLE
Not working again.

### ISSUE THREAD

**Issue by christopher0936** [eleventigers/mitsuku-api#5]
FINALLY got this to run (had to install it and say module globally, for some reason say isn't marked as a dependency even though it is), but am now having issues connecting. It seems pandorabots has blocked it somehow? I'm not sure how that's possible but it looks like they have? Is there some way to identify this api as separate from the webclient?

EDIT: forgot to mention, demo isn't working either.

**Comment by panichmaxim** [comment]
Rewrite api parser by yourself, looks like they found this repo.

**Comment by christopher0936** [comment]
api parser? how do I do that?

**Comment by eleventigers** [comment]
@christopher0936 try again, the bot endpoint has been updated.
