### ISSUE TITLE
Usage example don't work 

### ISSUE THREAD

**Issue by vladimirmyshkovski** [eleventigers/mitsuku-api#6]
```
var m = require('mitsuku-api')();

m.send('hello world')
  .then(function(response){
    console.log(response);
  });
```

 > This API is using Mitsuku without permission. Please visit www.mitsuku.com to talk to the genuine version of the chatbot.

Has anyone been able to send at least one request?

**Comment by eleventigers** [comment]
@narnikgamarnikus please try again, I have just updated the bot endpoint.
