### ISSUE TITLE
Error message?

### ISSUE THREAD

**Issue by prichey** [eleventigers/mitsuku-api#8]
I'm getting the following on any message request:

```
This app is using Mitsuku without permission.  Please do not support the leechers. You can email abuse@square-bear.co.uk with any questions or go to www.mitsuku.com to talk to the genuine version of the bot. - Steve Worswick.
```

Any ideas?

**Comment by SteveWorswick** [comment]
Check out the "Cease and Desist" notice from the chatbot owners in the closed issues. This guy has leeched the bot without permission and so has been stopped.

**Comment by prichey** [comment]
Ah, I see. Thanks @SteveWorswick
